import {default as metadata} from '../strings/metadata.json';

/* eslint-disable indent */

// Try to match a given culture with one in the list.
// return the closest match or nothing.
export function matchCulture(culture) {
	if (!culture) 
		return {};
	const ctrlLst = getCultures();
	
	// First, find an exact match.
	if (ctrlLst[culture]) 
		return ctrlLst[culture];
	
	// If culture is a child
	if (culture.indexOf('-') > 1) {
		let parentCulture = culture.split('-')[0];
		// find an exact match ot the parent.
		if (ctrlLst[parentCulture]) 
			return ctrlLst[parentCulture];
		// find a sister culture, pick the first found.
		for (var item in ctrlLst) {
			if (ctrlLst[item].ISO6391.split('-')[0] === parentCulture 
			|| ctrlLst[item].ISO6392.split('-')[0] === parentCulture)
				return ctrlLst[item];
		}
	} else {
		// otherwise try and find a child culture.
		// pick the first found.
		for (var item in ctrlLst) {
			if (ctrlLst[item].ISO6391.split('-')[0] === culture 
			|| ctrlLst[item].ISO6392.split('-')[0] === culture)
				return ctrlLst[item];
		}
	}
	
	return {};
}

// Import metadata file generated by 'mysource.py'.

export function getDictionaries() {
	return metadata;
}

export function getDictionary(ccode) {
	return metadata[ccode];
}

// List of cultures returned by the server
// list of native names taken from 
// https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code

var cultures = {
	  "ab": {
		"name": "Abkhazian",
		"displayName": "Abkhazian",
		"displayNativeName": "Аҧсуа",
		"ISO6391": "ab",
		"ISO6392": "abk",
		"ISO6392alt": [
		  "abk"
		]
	  },
	  "aa": {
		"name": "Afar",
		"displayName": "Afar",
		"displayNativeName": "Afar",
		"ISO6391": "aa",
		"ISO6392": "aar",
		"ISO6392alt": [
		  "aar"
		]
	  },
	  "af": {
		"name": "Afrikaans",
		"displayName": "Afrikaans",
		"displayNativeName": "Afrikaans",
		"ISO6391": "af",
		"ISO6392": "afr",
		"ISO6392alt": [
		  "afr"
		]
	  },
	  "ak": {
		"name": "Akan",
		"displayName": "Akan",
		"displayNativeName": "Akana",
		"ISO6391": "ak",
		"ISO6392": "aka",
		"ISO6392alt": [
		  "aka"
		]
	  },
	  "sq": {
		"name": "Albanian",
		"displayName": "Albanian",
		"displayNativeName": "Shqip",
		"ISO6391": "sq",
		"ISO6392": "alb",
		"ISO6392alt": [
		  "alb",
		  "sqi"
		]
	  },
	  "am": {
		"name": "Amharic",
		"displayName": "Amharic",
		"displayNativeName": "አማርኛ",
		"ISO6391": "am",
		"ISO6392": "amh",
		"ISO6392alt": [
		  "amh"
		]
	  },
	  "ar": {
		"name": "Arabic",
		"displayName": "Arabic",
		"displayNativeName": "العربية",
		"ISO6391": "ar",
		"ISO6392": "ara",
		"ISO6392alt": [
		  "ara"
		]
	  },
	  "an": {
		"name": "Aragonese",
		"displayName": "Aragonese",
		"displayNativeName": "Aragonés",
		"ISO6391": "an",
		"ISO6392": "arg",
		"ISO6392alt": [
		  "arg"
		]
	  },
	  "hy": {
		"name": "Armenian",
		"displayName": "Armenian",
		"displayNativeName": "Հայերեն",
		"ISO6391": "hy",
		"ISO6392": "arm",
		"ISO6392alt": [
		  "arm",
		  "hye"
		]
	  },
	  "as": {
		"name": "Assamese",
		"displayName": "Assamese",
		"displayNativeName": "অসমীয়া",
		"ISO6391": "as",
		"ISO6392": "asm",
		"ISO6392alt": [
		  "asm"
		]
	  },
	  "av": {
		"name": "Avaric",
		"displayName": "Avaric",
		"displayNativeName": "Авар",
		"ISO6391": "av",
		"ISO6392": "ava",
		"ISO6392alt": [
		  "ava"
		]
	  },
	  "ae": {
		"name": "Avestan",
		"displayName": "Avestan",
		"displayNativeName": "Avestan",
		"ISO6391": "ae",
		"ISO6392": "ave",
		"ISO6392alt": [
		  "ave"
		]
	  },
	  "ay": {
		"name": "Aymara",
		"displayName": "Aymara",
		"displayNativeName": "Aymar",
		"ISO6391": "ay",
		"ISO6392": "aym",
		"ISO6392alt": [
		  "aym"
		]
	  },
	  "az": {
		"name": "Azerbaijani",
		"displayName": "Azerbaijani",
		"displayNativeName": "Azərbaycanca",
		"ISO6391": "az",
		"ISO6392": "aze",
		"ISO6392alt": [
		  "aze"
		]
	  },
	  "bm": {
		"name": "Bambara",
		"displayName": "Bambara",
		"displayNativeName": "Bamanankan",
		"ISO6391": "bm",
		"ISO6392": "bam",
		"ISO6392alt": [
		  "bam"
		]
	  },
	  "ba": {
		"name": "Bashkir",
		"displayName": "Bashkir",
		"displayNativeName": "Башҡорт",
		"ISO6391": "ba",
		"ISO6392": "bak",
		"ISO6392alt": [
		  "bak"
		]
	  },
	  "eu": {
		"name": "Basque",
		"displayName": "Basque",
		"displayNativeName": "Euskara",
		"ISO6391": "eu",
		"ISO6392": "baq",
		"ISO6392alt": [
		  "baq",
		  "eus"
		]
	  },
	  "be-BY": {
		"name": "Belarusian",
		"displayName": "Belarusian",
		"displayNativeName": "Беларуская",
		"ISO6391": "be-BY",
		"ISO6392": "bel",
		"ISO6392alt": [
		  "bel"
		]
	  },
	  "bn-BD": {
		"name": "Bengali",
		"displayName": "Bengali",
		"displayNativeName": "বাংলা",
		"ISO6391": "bn-BD",
		"ISO6392": "ben",
		"ISO6392alt": [
		  "ben"
		]
	  },
	  "bh": {
		"name": "Bihari languages",
		"displayName": "Bihari languages",
		"displayNativeName": "भोजपुरी",
		"ISO6391": "bh",
		"ISO6392": "bih",
		"ISO6392alt": [
		  "bih"
		]
	  },
	  "bi": {
		"name": "Bislama",
		"displayName": "Bislama",
		"displayNativeName": "Bislama",
		"ISO6391": "bi",
		"ISO6392": "bis",
		"ISO6392alt": [
		  "bis"
		]
	  },
	  "bs": {
		"name": "Bosnian",
		"displayName": "Bosnian",
		"displayNativeName": "Bosanski",
		"ISO6391": "bs",
		"ISO6392": "bos",
		"ISO6392alt": [
		  "bos"
		]
	  },
	  "br": {
		"name": "Breton",
		"displayName": "Breton",
		"displayNativeName": "Brezhoneg",
		"ISO6391": "br",
		"ISO6392": "bre",
		"ISO6392alt": [
		  "bre"
		]
	  },
	  "bg-BG": {
		"name": "Bulgarian",
		"displayName": "Bulgarian",
		"displayNativeName": "Български",
		"ISO6391": "bg-BG",
		"ISO6392": "bul",
		"ISO6392alt": [
		  "bul"
		]
	  },
	  "my": {
		"name": "Burmese",
		"displayName": "Burmese",
		"displayNativeName": "Myanmasa",
		"ISO6391": "my",
		"ISO6392": "bur",
		"ISO6392alt": [
		  "bur",
		  "mya"
		]
	  },
	  "ca": {
		"name": "Catalan; Valencian",
		"displayName": "Catalan; Valencian",
		"displayNativeName": "Català",
		"ISO6391": "ca",
		"ISO6392": "cat",
		"ISO6392alt": [
		  "cat"
		]
	  },
	  "km": {
		"name": "Central Khmer",
		"displayName": "Central Khmer",
		"displayNativeName": "ភាសាខ្មែរ",
		"ISO6391": "km",
		"ISO6392": "khm",
		"ISO6392alt": [
		  "khm"
		]
	  },
	  "ch": {
		"name": "Chamorro",
		"displayName": "Chamorro",
		"displayNativeName": "Chamoru",
		"ISO6391": "ch",
		"ISO6392": "cha",
		"ISO6392alt": [
		  "cha"
		]
	  },
	  "ce": {
		"name": "Chechen",
		"displayName": "Chechen",
		"displayNativeName": "Нохчийн",
		"ISO6391": "ce",
		"ISO6392": "che",
		"ISO6392alt": [
		  "che"
		]
	  },
	  "ny": {
		"name": "Chichewa; Chewa; Nyanja",
		"displayName": "Chichewa; Chewa; Nyanja",
		"displayNativeName": "Chi-Chewa",
		"ISO6391": "ny",
		"ISO6392": "nya",
		"ISO6392alt": [
		  "nya"
		]
	  },
	  "zh-CN": {
		"name": "Chinese",
		"displayName": "Chinese",
		"displayNativeName": "中文",
		"ISO6391": "zh-CN",
		"ISO6392": "chi",
		"ISO6392alt": [
		  "chi",
		  "zho"
		]
	  },
	  "zh-HK": {
		"name": "Chinese; Hong Kong",
		"displayName": "Chinese; Hong Kong",
		"displayNativeName": "廣東話 (香港)",
		"ISO6391": "zh-HK",
		"ISO6392": "chi",
		"ISO6392alt": [
		  "chi",
		  "zho"
		]
	  },
	  "zh-TW": {
		"name": "Chinese; Traditional",
		"displayName": "Chinese; Traditional",
		"displayNativeName": "中文(台灣)‬",
		"ISO6391": "zh-TW",
		"ISO6392": "chi",
		"ISO6392alt": [
		  "chi",
		  "zho"
		]
	  },
	  "cu": {
		"name": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
		"displayName": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
		"displayNativeName": "словѣньскъ",
		"ISO6391": "cu",
		"ISO6392": "chu",
		"ISO6392alt": [
		  "chu"
		]
	  },
	  "cv": {
		"name": "Chuvash",
		"displayName": "Chuvash",
		"displayNativeName": "Чăваш",
		"ISO6391": "cv",
		"ISO6392": "chv",
		"ISO6392alt": [
		  "chv"
		]
	  },
	  "kw": {
		"name": "Cornish",
		"displayName": "Cornish",
		"displayNativeName": "Kernewek",
		"ISO6391": "kw",
		"ISO6392": "cor",
		"ISO6392alt": [
		  "cor"
		]
	  },
	  "co": {
		"name": "Corsican",
		"displayName": "Corsican",
		"displayNativeName": "Corsu",
		"ISO6391": "co",
		"ISO6392": "cos",
		"ISO6392alt": [
		  "cos"
		]
	  },
	  "cr": {
		"name": "Cree",
		"displayName": "Cree",
		"displayNativeName": "Nehiyaw",
		"ISO6391": "cr",
		"ISO6392": "cre",
		"ISO6392alt": [
		  "cre"
		]
	  },
	  "hr": {
		"name": "Croatian",
		"displayName": "Croatian",
		"displayNativeName": "Hrvatski",
		"ISO6391": "hr",
		"ISO6392": "hrv",
		"ISO6392alt": [
		  "hrv"
		]
	  },
	  "cs": {
		"name": "Czech",
		"displayName": "Czech",
		"displayNativeName": "Česky",
		"ISO6391": "cs",
		"ISO6392": "cze",
		"ISO6392alt": [
		  "cze",
		  "ces"
		]
	  },
	  "da": {
		"name": "Danish",
		"displayName": "Danish",
		"displayNativeName": "Dansk",
		"ISO6391": "da",
		"ISO6392": "dan",
		"ISO6392alt": [
		  "dan"
		]
	  },
	  "dv": {
		"name": "Divehi; Dhivehi; Maldivian",
		"displayName": "Divehi; Dhivehi; Maldivian",
		"displayNativeName": "Divehi",
		"ISO6391": "dv",
		"ISO6392": "div",
		"ISO6392alt": [
		  "div"
		]
	  },
	  "nl": {
		"name": "Dutch; Flemish",
		"displayName": "Dutch; Flemish",
		"displayNativeName": "Nederlands",
		"ISO6391": "nl",
		"ISO6392": "dut",
		"ISO6392alt": [
		  "dut",
		  "nld"
		]
	  },
	  "dz": {
		"name": "Dzongkha",
		"displayName": "Dzongkha",
		"displayNativeName": "Dzongkha",
		"ISO6391": "dz",
		"ISO6392": "dzo",
		"ISO6392alt": [
		  "dzo"
		]
	  },
	  "en-US": {
		"name": "English",
		"displayName": "English",
		"displayNativeName": "English",
		"ISO6391": "en-US",
		"ISO6392": "eng",
		"ISO6392alt": [
		  "eng"
		]
	  },
	  "en-GB": {
		"displayName": "English, Great Britain",
		"displayNativeName": "English, Great Britain",
		"ISO6391": "en-GB",
		"ISO6392": "en-GB",
		"ISO6392alt": [
		  "eng"
		]
	  },
	  "eo": {
		"name": "Esperanto",
		"displayName": "Esperanto",
		"displayNativeName": "Esperanto",
		"ISO6391": "eo",
		"ISO6392": "epo",
		"ISO6392alt": [
		  "epo"
		]
	  },
	  "et": {
		"name": "Estonian",
		"displayName": "Estonian",
		"displayNativeName": "Eesti",
		"ISO6391": "et",
		"ISO6392": "est",
		"ISO6392alt": [
		  "est"
		]
	  },
	  "ee": {
		"name": "Ewe",
		"displayName": "Ewe",
		"displayNativeName": "Ɛʋɛ",
		"ISO6391": "ee",
		"ISO6392": "ewe",
		"ISO6392alt": [
		  "ewe"
		]
	  },
	  "fo": {
		"name": "Faroese",
		"displayName": "Faroese",
		"displayNativeName": "Føroyskt",
		"ISO6391": "fo",
		"ISO6392": "fao",
		"ISO6392alt": [
		  "fao"
		]
	  },
	  "fj": {
		"name": "Fijian",
		"displayName": "Fijian",
		"displayNativeName": "Na Vosa Vakaviti",
		"ISO6391": "fj",
		"ISO6392": "fij",
		"ISO6392alt": [
		  "fij"
		]
	  },
	  "fil": {
		"name": "Filipino",
		"displayName": "Filipino",
		"displayNativeName": "Filipino",
		"ISO6391": "fil",
		"ISO6392": "fil",
		"ISO6392alt": [
		  "fil"
		]
	  },
	  "fi": {
		"name": "Finnish",
		"displayName": "Finnish",
		"displayNativeName": "Suomi",
		"ISO6391": "fi",
		"ISO6392": "fin",
		"ISO6392alt": [
		  "fin"
		]
	  },
	  "fr": {
		"name": "French",
		"displayName": "French",
		"displayNativeName": "Français",
		"ISO6391": "fr",
		"ISO6392": "fre",
		"ISO6392alt": [
		  "fre",
		  "fra"
		]
	  },
	  "fr-CA": {
		"name": "French, Canada",
		"displayName": "French, Canada",
		"displayNativeName": "Français, Canada",
		"ISO6391": "fr-CA",
		"ISO6392": "frc",
		"ISO6392alt": [
		  "frc"
		]
	  },
	  "ff": {
		"name": "Fulah",
		"displayName": "Fulah",
		"displayNativeName": "Fulfulde",
		"ISO6391": "ff",
		"ISO6392": "ful",
		"ISO6392alt": [
		  "ful"
		]
	  },
	  "gd": {
		"name": "Gaelic; Scottish Gaelic",
		"displayName": "Gaelic; Scottish Gaelic",
		"displayNativeName": "Gàidhlig",
		"ISO6391": "gd",
		"ISO6392": "gla",
		"ISO6392alt": [
		  "gla"
		]
	  },
	  "gl": {
		"name": "Galician",
		"displayName": "Galician",
		"displayNativeName": "Galego",
		"ISO6391": "gl",
		"ISO6392": "glg",
		"ISO6392alt": [
		  "glg"
		]
	  },
	  "lg": {
		"name": "Ganda",
		"displayName": "Ganda",
		"displayNativeName": "Luganda",
		"ISO6391": "lg",
		"ISO6392": "lug",
		"ISO6392alt": [
		  "lug"
		]
	  },
	  "ka": {
		"name": "Georgian",
		"displayName": "Georgian",
		"displayNativeName": "ქართული",
		"ISO6391": "ka",
		"ISO6392": "geo",
		"ISO6392alt": [
		  "geo",
		  "kat"
		]
	  },
	  "de": {
		"name": "German",
		"displayName": "German",
		"displayNativeName": "Deutsch",
		"ISO6391": "de",
		"ISO6392": "ger",
		"ISO6392alt": [
		  "ger",
		  "deu"
		]
	  },
	  "el": {
		"name": "Greek, Modern (1453-)",
		"displayName": "Greek, Modern (1453-)",
		"displayNativeName": "Ελληνικά",
		"ISO6391": "el",
		"ISO6392": "gre",
		"ISO6392alt": [
		  "gre",
		  "ell"
		]
	  },
	  "gn": {
		"name": "Guarani",
		"displayName": "Guarani",
		"displayNativeName": "Avañe'ẽ",
		"ISO6391": "gn",
		"ISO6392": "grn",
		"ISO6392alt": [
		  "grn"
		]
	  },
	  "gu": {
		"name": "Gujarati",
		"displayName": "Gujarati",
		"displayNativeName": "ગુજરાતી",
		"ISO6391": "gu",
		"ISO6392": "guj",
		"ISO6392alt": [
		  "guj"
		]
	  },
	  "ht": {
		"name": "Haitian; Haitian Creole",
		"displayName": "Haitian; Haitian Creole",
		"displayNativeName": "Krèyol ayisyen",
		"ISO6391": "ht",
		"ISO6392": "hat",
		"ISO6392alt": [
		  "hat"
		]
	  },
	  "ha": {
		"name": "Hausa",
		"displayName": "Hausa",
		"displayNativeName": "هَوُسَ",
		"ISO6391": "ha",
		"ISO6392": "hau",
		"ISO6392alt": [
		  "hau"
		]
	  },
	  "he": {
		"name": "Hebrew",
		"displayName": "Hebrew",
		"displayNativeName": "עברית",
		"ISO6391": "he",
		"ISO6392": "heb",
		"ISO6392alt": [
		  "heb"
		]
	  },
	  "hz": {
		"name": "Herero",
		"displayName": "Herero",
		"displayNativeName": "Otsiherero",
		"ISO6391": "hz",
		"ISO6392": "her",
		"ISO6392alt": [
		  "her"
		]
	  },
	  "hi-IN": {
		"name": "Hindi",
		"displayName": "Hindi",
		"displayNativeName": "हिन्दी",
		"ISO6391": "hi-IN",
		"ISO6392": "hin",
		"ISO6392alt": [
		  "hin"
		]
	  },
	  "ho": {
		"name": "Hiri Motu",
		"displayName": "Hiri Motu",
		"displayNativeName": "Hiri Motu",
		"ISO6391": "ho",
		"ISO6392": "hmo",
		"ISO6392alt": [
		  "hmo"
		]
	  },
	  "hu": {
		"name": "Hungarian",
		"displayName": "Hungarian",
		"displayNativeName": "Magyar",
		"ISO6391": "hu",
		"ISO6392": "hun",
		"ISO6392alt": [
		  "hun"
		]
	  },
	  "is-IS": {
		"name": "Icelandic",
		"displayName": "Icelandic",
		"displayNativeName": "Íslenska",
		"ISO6391": "is-IS",
		"ISO6392": "ice",
		"ISO6392alt": [
		  "ice",
		  "isl"
		]
	  },
	  "io": {
		"name": "Ido",
		"displayName": "Ido",
		"displayNativeName": "Ido",
		"ISO6391": "io",
		"ISO6392": "ido",
		"ISO6392alt": [
		  "ido"
		]
	  },
	  "ig": {
		"name": "Igbo",
		"displayName": "Igbo",
		"displayNativeName": "Igbo",
		"ISO6391": "ig",
		"ISO6392": "ibo",
		"ISO6392alt": [
		  "ibo"
		]
	  },
	  "id": {
		"name": "Indonesian",
		"displayName": "Indonesian",
		"displayNativeName": "Bahasa Indonesia",
		"ISO6391": "id",
		"ISO6392": "ind",
		"ISO6392alt": [
		  "ind"
		]
	  },
	  "ia": {
		"name": "Interlingua (International Auxiliary Language Association)",
		"displayName": "Interlingua (International Auxiliary Language Association)",
		"displayNativeName": "Interlingua",
		"ISO6391": "ia",
		"ISO6392": "ina",
		"ISO6392alt": [
		  "ina"
		]
	  },
	  "ie": {
		"name": "Interlingue; Occidental",
		"displayName": "Interlingue; Occidental",
		"displayNativeName": "Interlingue",
		"ISO6391": "ie",
		"ISO6392": "ile",
		"ISO6392alt": [
		  "ile"
		]
	  },
	  "iu": {
		"name": "Inuktitut",
		"displayName": "Inuktitut",
		"displayNativeName": "Inuktitut",
		"ISO6391": "iu",
		"ISO6392": "iku",
		"ISO6392alt": [
		  "iku"
		]
	  },
	  "ik": {
		"name": "Inupiaq",
		"displayName": "Inupiaq",
		"displayNativeName": "Iñupiak",
		"ISO6391": "ik",
		"ISO6392": "ipk",
		"ISO6392alt": [
		  "ipk"
		]
	  },
	  "ga": {
		"name": "Irish",
		"displayName": "Irish",
		"displayNativeName": "Gaeilge",
		"ISO6391": "ga",
		"ISO6392": "gle",
		"ISO6392alt": [
		  "gle"
		]
	  },
	  "it": {
		"name": "Italian",
		"displayName": "Italian",
		"displayNativeName": "Italiano",
		"ISO6391": "it",
		"ISO6392": "ita",
		"ISO6392alt": [
		  "ita"
		]
	  },
	  "ja": {
		"name": "Japanese",
		"displayName": "Japanese",
		"displayNativeName": "日本語",
		"ISO6391": "ja",
		"ISO6392": "jpn",
		"ISO6392alt": [
		  "jpn"
		]
	  },
	  "jv": {
		"name": "Javanese",
		"displayName": "Javanese",
		"displayNativeName": "Basa Jawa",
		"ISO6391": "jv",
		"ISO6392": "jav",
		"ISO6392alt": [
		  "jav"
		]
	  },
	  "kl": {
		"name": "Kalaallisut; Greenlandic",
		"displayName": "Kalaallisut; Greenlandic",
		"displayNativeName": "Kalaallisut",
		"ISO6391": "kl",
		"ISO6392": "kal",
		"ISO6392alt": [
		  "kal"
		]
	  },
	  "kn": {
		"name": "Kannada",
		"displayName": "Kannada",
		"displayNativeName": "ಕನ್ನಡ",
		"ISO6391": "kn",
		"ISO6392": "kan",
		"ISO6392alt": [
		  "kan"
		]
	  },
	  "kr": {
		"name": "Kanuri",
		"displayName": "Kanuri",
		"displayNativeName": "Kanuri",
		"ISO6391": "kr",
		"ISO6392": "kau",
		"ISO6392alt": [
		  "kau"
		]
	  },
	  "ks": {
		"name": "Kashmiri",
		"displayName": "Kashmiri",
		"displayNativeName": "कॉशुर",
		"ISO6391": "ks",
		"ISO6392": "kas",
		"ISO6392alt": [
		  "kas"
		]
	  },
	  "kk": {
		"name": "Kazakh",
		"displayName": "Kazakh",
		"displayNativeName": "Қазақша",
		"ISO6391": "kk",
		"ISO6392": "kaz",
		"ISO6392alt": [
		  "kaz"
		]
	  },
	  "ki": {
		"name": "Kikuyu; Gikuyu",
		"displayName": "Kikuyu; Gikuyu",
		"displayNativeName": "Gĩkũyũ",
		"ISO6391": "ki",
		"ISO6392": "kik",
		"ISO6392alt": [
		  "kik"
		]
	  },
	  "rw": {
		"name": "Kinyarwanda",
		"displayName": "Kinyarwanda",
		"displayNativeName": "Kinyarwandi",
		"ISO6391": "rw",
		"ISO6392": "kin",
		"ISO6392alt": [
		  "kin"
		]
	  },
	  "ky": {
		"name": "Kirghiz; Kyrgyz",
		"displayName": "Kirghiz; Kyrgyz",
		"displayNativeName": "Кыргызча",
		"ISO6391": "ky",
		"ISO6392": "kir",
		"ISO6392alt": [
		  "kir"
		]
	  },
	  "kv": {
		"name": "Komi",
		"displayName": "Komi",
		"displayNativeName": "Коми",
		"ISO6391": "kv",
		"ISO6392": "kom",
		"ISO6392alt": [
		  "kom"
		]
	  },
	  "kg": {
		"name": "Kongo",
		"displayName": "Kongo",
		"displayNativeName": "KiKongo",
		"ISO6391": "kg",
		"ISO6392": "kon",
		"ISO6392alt": [
		  "kon"
		]
	  },
	  "ko": {
		"name": "Korean",
		"displayName": "Korean",
		"displayNativeName": "한국어",
		"ISO6391": "ko",
		"ISO6392": "kor",
		"ISO6392alt": [
		  "kor"
		]
	  },
	  "kj": {
		"name": "Kuanyama; Kwanyama",
		"displayName": "Kuanyama; Kwanyama",
		"displayNativeName": "Kuanyama",
		"ISO6391": "kj",
		"ISO6392": "kua",
		"ISO6392alt": [
		  "kua"
		]
	  },
	  "ku": {
		"name": "Kurdish",
		"displayName": "Kurdish",
		"displayNativeName": "Kurdî",
		"ISO6391": "ku",
		"ISO6392": "kur",
		"ISO6392alt": [
		  "kur"
		]
	  },
	  "lo": {
		"name": "Lao",
		"displayName": "Lao",
		"displayNativeName": "Pha xa lao",
		"ISO6391": "lo",
		"ISO6392": "lao",
		"ISO6392alt": [
		  "lao"
		]
	  },
	  "la": {
		"name": "Latin",
		"displayName": "Latin",
		"displayNativeName": "Latina",
		"ISO6391": "la",
		"ISO6392": "lat",
		"ISO6392alt": [
		  "lat"
		]
	  },
	  "lv": {
		"name": "Latvian",
		"displayName": "Latvian",
		"displayNativeName": "Latviešu",
		"ISO6391": "lv",
		"ISO6392": "lav",
		"ISO6392alt": [
		  "lav"
		]
	  },
	  "li": {
		"name": "Limburgan; Limburger; Limburgish",
		"displayName": "Limburgan; Limburger; Limburgish",
		"displayNativeName": "Limburgs",
		"ISO6391": "li",
		"ISO6392": "lim",
		"ISO6392alt": [
		  "lim"
		]
	  },
	  "ln": {
		"name": "Lingala",
		"displayName": "Lingala",
		"displayNativeName": "Lingála",
		"ISO6391": "ln",
		"ISO6392": "lin",
		"ISO6392alt": [
		  "lin"
		]
	  },
	  "lt-LT": {
		"name": "Lithuanian",
		"displayName": "Lithuanian",
		"displayNativeName": "Lietuvių",
		"ISO6391": "lt-LT",
		"ISO6392": "lit",
		"ISO6392alt": [
		  "lit"
		]
	  },
	  "lu": {
		"name": "Luba-Katanga",
		"displayName": "Luba-Katanga",
		"displayNativeName": "Luba-Katanga",
		"ISO6391": "lu",
		"ISO6392": "lub",
		"ISO6392alt": [
		  "lub"
		]
	  },
	  "lb": {
		"name": "Luxembourgish; Letzeburgesch",
		"displayName": "Luxembourgish; Letzeburgesch",
		"displayNativeName": "Lëtzebuergesch",
		"ISO6391": "lb",
		"ISO6392": "ltz",
		"ISO6392alt": [
		  "ltz"
		]
	  },
	  "mk": {
		"name": "Macedonian",
		"displayName": "Macedonian",
		"displayNativeName": "Македонски",
		"ISO6391": "mk",
		"ISO6392": "mac",
		"ISO6392alt": [
		  "mac",
		  "mkd"
		]
	  },
	  "mg": {
		"name": "Malagasy",
		"displayName": "Malagasy",
		"displayNativeName": "Malagasy",
		"ISO6391": "mg",
		"ISO6392": "mlg",
		"ISO6392alt": [
		  "mlg"
		]
	  },
	  "ms": {
		"name": "Malay",
		"displayName": "Malay",
		"displayNativeName": "Bahasa Melayu",
		"ISO6391": "ms",
		"ISO6392": "may",
		"ISO6392alt": [
		  "may",
		  "msa"
		]
	  },
	  "ml": {
		"name": "Malayalam",
		"displayName": "Malayalam",
		"displayNativeName": "മലയാളം",
		"ISO6391": "ml",
		"ISO6392": "mal",
		"ISO6392alt": [
		  "mal"
		]
	  },
	  "mt": {
		"name": "Maltese",
		"displayName": "Maltese",
		"displayNativeName": "bil-Malti ",
		"ISO6391": "mt",
		"ISO6392": "mlt",
		"ISO6392alt": [
		  "mlt"
		]
	  },
	  "gv": {
		"name": "Manx",
		"displayName": "Manx",
		"displayNativeName": "Gaelg",
		"ISO6391": "gv",
		"ISO6392": "glv",
		"ISO6392alt": [
		  "glv"
		]
	  },
	  "mi": {
		"name": "Maori",
		"displayName": "Maori",
		"displayNativeName": "Māori",
		"ISO6391": "mi",
		"ISO6392": "mao",
		"ISO6392alt": [
		  "mao",
		  "mri"
		]
	  },
	  "mr": {
		"name": "Marathi",
		"displayName": "Marathi",
		"displayNativeName": "मराठी",
		"ISO6391": "mr",
		"ISO6392": "mar",
		"ISO6392alt": [
		  "mar"
		]
	  },
	  "mh": {
		"name": "Marshallese",
		"displayName": "Marshallese",
		"displayNativeName": "Kajin Majel",
		"ISO6391": "mh",
		"ISO6392": "mah",
		"ISO6392alt": [
		  "mah"
		]
	  },
	  "mn": {
		"name": "Mongolian",
		"displayName": "Mongolian",
		"displayNativeName": "Монгол",
		"ISO6391": "mn",
		"ISO6392": "mon",
		"ISO6392alt": [
		  "mon"
		]
	  },
	  "na": {
		"name": "Nauru",
		"displayName": "Nauru",
		"displayNativeName": "Dorerin Naoero",
		"ISO6391": "na",
		"ISO6392": "nau",
		"ISO6392alt": [
		  "nau"
		]
	  },
	  "nv": {
		"name": "Navajo; Navaho",
		"displayName": "Navajo; Navaho",
		"displayNativeName": "Diné bizaad",
		"ISO6391": "nv",
		"ISO6392": "nav",
		"ISO6392alt": [
		  "nav"
		]
	  },
	  "nd": {
		"name": "Ndebele, North; North Ndebele",
		"displayName": "Ndebele, North; North Ndebele",
		"displayNativeName": "Sindebele",
		"ISO6391": "nd",
		"ISO6392": "nde",
		"ISO6392alt": [
		  "nde"
		]
	  },
	  "nr": {
		"name": "Ndebele, South; South Ndebele",
		"displayName": "Ndebele, South; South Ndebele",
		"displayNativeName": "isiNdebele",
		"ISO6391": "nr",
		"ISO6392": "nbl",
		"ISO6392alt": [
		  "nbl"
		]
	  },
	  "ng": {
		"name": "Ndonga",
		"displayName": "Ndonga",
		"displayNativeName": "Oshiwambo",
		"ISO6391": "ng",
		"ISO6392": "ndo",
		"ISO6392alt": [
		  "ndo"
		]
	  },
	  "ne": {
		"name": "Nepali",
		"displayName": "Nepali",
		"displayNativeName": "नेपाली",
		"ISO6391": "ne",
		"ISO6392": "nep",
		"ISO6392alt": [
		  "nep"
		]
	  },
	  "se": {
		"name": "Northern Sami",
		"displayName": "Northern Sami",
		"displayNativeName": "Davvisámegiella",
		"ISO6391": "se",
		"ISO6392": "sme",
		"ISO6392alt": [
		  "sme"
		]
	  },
	  "no": {
		"name": "Norwegian",
		"displayName": "Norwegian",
		"displayNativeName": "Norsk",
		"ISO6391": "no",
		"ISO6392": "nor",
		"ISO6392alt": [
		  "nor"
		]
	  },
	  "nn": {
		"name": "Norwegian, Nynorsk",
		"displayName": "Norwegian, Nynorsk",
		"displayNativeName": "Norsk, Nynorsk ",
		"ISO6391": "nn",
		"ISO6392": "nno",
		"ISO6392alt": [
		  "nno"
		]
	  },
	  "nb": {
		"name": "Norwegian, Bokmål",
		"displayName": "Norwegian, Bokmål",
		"displayNativeName": "Norsk, Bokmål",
		"ISO6391": "nb",
		"ISO6392": "nob",
		"ISO6392alt": [
		  "nob"
		]
	  },
	  "oc": {
		"name": "Occitan (post 1500); Provençal",
		"displayName": "Occitan (post 1500); Provençal",
		"displayNativeName": "Occitan",
		"ISO6391": "oc",
		"ISO6392": "oci",
		"ISO6392alt": [
		  "oci"
		]
	  },
	  "oj": {
		"name": "Ojibwa",
		"displayName": "Ojibwa",
		"displayNativeName": "Ojibwa",
		"ISO6391": "oj",
		"ISO6392": "oji",
		"ISO6392alt": [
		  "oji"
		]
	  },
	  "or": {
		"name": "Oriya",
		"displayName": "Oriya",
		"displayNativeName": "ଓଡ଼ିଆ",
		"ISO6391": "or",
		"ISO6392": "ori",
		"ISO6392alt": [
		  "ori"
		]
	  },
	  "om": {
		"name": "Oromo",
		"displayName": "Oromo",
		"displayNativeName": "Oromoo",
		"ISO6391": "om",
		"ISO6392": "orm",
		"ISO6392alt": [
		  "orm"
		]
	  },
	  "os": {
		"name": "Ossetian; Ossetic",
		"displayName": "Ossetian; Ossetic",
		"displayNativeName": "Иронау",
		"ISO6391": "os",
		"ISO6392": "oss",
		"ISO6392alt": [
		  "oss"
		]
	  },
	  "pi": {
		"name": "Pali",
		"displayName": "Pali",
		"displayNativeName": "Pāli",
		"ISO6391": "pi",
		"ISO6392": "pli",
		"ISO6392alt": [
		  "pli"
		]
	  },
	  "pa": {
		"name": "Panjabi; Punjabi",
		"displayName": "Panjabi; Punjabi",
		"displayNativeName": "ਪੰਜਾਬੀ",
		"ISO6391": "pa",
		"ISO6392": "pan",
		"ISO6392alt": [
		  "pan"
		]
	  },
	  "fa": {
		"name": "Persian",
		"displayName": "Persian",
		"displayNativeName": "فارسی",
		"ISO6391": "fa",
		"ISO6392": "per",
		"ISO6392alt": [
		  "per",
		  "fas"
		]
	  },
	  "pl": {
		"name": "Polish",
		"displayName": "Polish",
		"displayNativeName": "Polski",
		"ISO6391": "pl",
		"ISO6392": "pol",
		"ISO6392alt": [
		  "pol"
		]
	  },
	  "pr": {
		"name": "Pirate",
		"displayName": "Pirate",
		"displayNativeName": "Pirate",
		"ISO6391": "pr",
		"ISO6392": "pir",
		"ISO6392alt": [
		  "pir"
		]
	  },
	  "pt": {
		"name": "Portuguese",
		"displayName": "Portuguese",
		"displayNativeName": "Português",
		"ISO6391": "pt",
		"ISO6392": "prt",
		"ISO6392alt": [
		  "por"
		]
	  },
	  "pt-PT": {
		"name": "Portuguese",
		"displayName": "Portuguese, Portugal",
		"displayNativeName": "Português, Portugal",
		"ISO6391": "pt-PT",
		"ISO6392": "por",
		"ISO6392alt": [
		  "por"
		]
	  },
	  "pt-BR": {
		"name": "Portuguese, Brazil",
		"displayName": "Portuguese, Brazil",
		"displayNativeName": "Português, Brazil",
		"ISO6391": "pt-BR",
		"ISO6392": "pob",
		"ISO6392alt": [
		  "pob"
		]
	  },
	  "ps": {
		"name": "Pushto; Pashto",
		"displayName": "Pushto; Pashto",
		"displayNativeName": "پښتو",
		"ISO6391": "ps",
		"ISO6392": "pus",
		"ISO6392alt": [
		  "pus"
		]
	  },
	  "qu": {
		"name": "Quechua",
		"displayName": "Quechua",
		"displayNativeName": "Runa Simi",
		"ISO6391": "qu",
		"ISO6392": "que",
		"ISO6392alt": [
		  "que"
		]
	  },
	  "ro": {
		"name": "Romanian; Moldavian; Moldovan",
		"displayName": "Romanian; Moldavian; Moldovan",
		"displayNativeName": "Română",
		"ISO6391": "ro",
		"ISO6392": "rum",
		"ISO6392alt": [
		  "rum",
		  "ron"
		]
	  },
	  "rm": {
		"name": "Romansh",
		"displayName": "Romansh",
		"displayNativeName": "rumantsch",
		"ISO6391": "rm",
		"ISO6392": "roh",
		"ISO6392alt": [
		  "roh"
		]
	  },
	  "rn": {
		"name": "Rundi",
		"displayName": "Rundi",
		"displayNativeName": "kirundi",
		"ISO6391": "rn",
		"ISO6392": "run",
		"ISO6392alt": [
		  "run"
		]
	  },
	  "ru": {
		"name": "Russian",
		"displayName": "Russian",
		"displayNativeName": "Русский",
		"ISO6391": "ru",
		"ISO6392": "rus",
		"ISO6392alt": [
		  "rus"
		]
	  },
	  "sm": {
		"name": "Samoan",
		"displayName": "Samoan",
		"displayNativeName": "Gagana Samoa",
		"ISO6391": "sm",
		"ISO6392": "smo",
		"ISO6392alt": [
		  "smo"
		]
	  },
	  "sg": {
		"name": "Sango",
		"displayName": "Sango",
		"displayNativeName": "Sängö",
		"ISO6391": "sg",
		"ISO6392": "sag",
		"ISO6392alt": [
		  "sag"
		]
	  },
	  "sa": {
		"name": "Sanskrit",
		"displayName": "Sanskrit",
		"displayNativeName": "संस्कृतम्",
		"ISO6391": "sa",
		"ISO6392": "san",
		"ISO6392alt": [
		  "san"
		]
	  },
	  "sc": {
		"name": "Sardinian",
		"displayName": "Sardinian",
		"displayNativeName": "Sardu",
		"ISO6391": "sc",
		"ISO6392": "srd",
		"ISO6392alt": [
		  "srd"
		]
	  },
	  "sr": {
		"name": "Serbian",
		"displayName": "Serbian",
		"displayNativeName": "Српски",
		"ISO6391": "sr",
		"ISO6392": "srp",
		"ISO6392alt": [
		  "srp",
		  "scc"
		]
	  },
	  "sn": {
		"name": "Shona",
		"displayName": "Shona",
		"displayNativeName": "chiShona",
		"ISO6391": "sn",
		"ISO6392": "sna",
		"ISO6392alt": [
		  "sna"
		]
	  },
	  "ii": {
		"name": "Sichuan Yi; Nuosu",
		"displayName": "Sichuan Yi; Nuosu",
		"displayNativeName": "Sichuan Yi",
		"ISO6391": "ii",
		"ISO6392": "iii",
		"ISO6392alt": [
		  "iii"
		]
	  },
	  "sd": {
		"name": "Sindhi",
		"displayName": "Sindhi",
		"displayNativeName": "سنڌي",
		"ISO6391": "sd",
		"ISO6392": "snd",
		"ISO6392alt": [
		  "snd"
		]
	  },
	  "si": {
		"name": "Sinhala, Sinhalese",
		"displayName": "Sinhala; Sinhalese",
		"displayNativeName": "සිංහල",
		"ISO6391": "si",
		"ISO6392": "sin",
		"ISO6392alt": [
		  "sin"
		]
	  },
	  "sk": {
		"name": "Slovak",
		"displayName": "Slovak",
		"displayNativeName": "Slovenčina",
		"ISO6391": "sk",
		"ISO6392": "slo",
		"ISO6392alt": [
		  "slo",
		  "slk"
		]
	  },
	  "sl-SI": {
		"name": "Slovenian",
		"displayName": "Slovenian",
		"displayNativeName": "Slovenščina",
		"ISO6391": "sl-SI",
		"ISO6392": "slv",
		"ISO6392alt": [
		  "slv"
		]
	  },
	  "so": {
		"name": "Somali",
		"displayName": "Somali",
		"displayNativeName": "Soomaaliga",
		"ISO6391": "so",
		"ISO6392": "som",
		"ISO6392alt": [
		  "som"
		]
	  },
	  "st": {
		"name": "Sotho, Southern",
		"displayName": "Sotho, Southern",
		"displayNativeName": "Sesotho",
		"ISO6391": "st",
		"ISO6392": "sot",
		"ISO6392alt": [
		  "sot"
		]
	  },
	  "es-AR": {
		"displayName": "Spanish, Argentina",
		"displayNativeName": "Español, República Argentina",
		"ISO6391": "es-AR",
		"ISO6392": "es-AR",
		"ISO6392alt": [
		  "spa"
		]
	  },
	  "es-DO": {
		"displayName": "Spanish, Dominican Republic",
		"displayNativeName": "Español, República Dominicana",
		"ISO6391": "es-DO",
		"ISO6392": "es-DO",
		"ISO6392alt": [
		  "spa"
		]
	  },
	  "es-419": {
		"displayName": "Spanish, Latin America",
		"displayNativeName": "Español, América Latina",
		"ISO6391": "es-419",
		"ISO6392": "es-419",
		"ISO6392alt": [
		  "spa"
		]
	  },
	  "es": {
		"name": "Spanish; castellano",
		"displayName": "Spanish, castellano",
		"displayNativeName": "Español, castellano",
		"ISO6391": "es",
		"ISO6392": "spa",
		"ISO6392alt": [
		  "spa"
		]
	  },
	  "es-MX": {
		"name": "Spanish; Latin",
		"displayName": "Spanish, Mexico",
		"displayNativeName": "Español, Mexico",
		"ISO6391": "es-MX",
		"ISO6392": "es-MX",
		"ISO6392alt": [
		  "spa"
		]
	  },
	  "su": {
		"name": "Sundanese",
		"displayName": "Sundanese",
		"displayNativeName": "Basa Sunda",
		"ISO6391": "su",
		"ISO6392": "sun",
		"ISO6392alt": [
		  "sun"
		]
	  },
	  "sw": {
		"name": "Swahili",
		"displayName": "Swahili",
		"displayNativeName": "Kiswahili",
		"ISO6391": "sw",
		"ISO6392": "swa",
		"ISO6392alt": [
		  "swa"
		]
	  },
	  "ss": {
		"name": "Swati",
		"displayName": "Swati",
		"displayNativeName": "SiSwati",
		"ISO6391": "ss",
		"ISO6392": "ssw",
		"ISO6392alt": [
		  "ssw"
		]
	  },
	  "sv": {
		"name": "Swedish",
		"displayName": "Swedish",
		"displayNativeName": "Svenska",
		"ISO6391": "sv",
		"ISO6392": "swe",
		"ISO6392alt": [
		  "swe"
		]
	  },
	  "gsw": {
		"name": "Swiss German; Alemannic; Alsatian",
		"displayName": "Swiss German; Alemannic; Alsatian",
		"displayNativeName": "Alemannisch",
		"ISO6391": "gsw",
		"ISO6392": "gsw",
		"ISO6392alt": [
		  "gsw"
		]
	  },
	  "tl": {
		"name": "Tagalog",
		"displayName": "Tagalog",
		"displayNativeName": "Tagalog",
		"ISO6391": "tl",
		"ISO6392": "tgl",
		"ISO6392alt": [
		  "tgl"
		]
	  },
	  "ty": {
		"name": "Tahitian",
		"displayName": "Tahitian",
		"displayNativeName": "Reo Mā`ohi",
		"ISO6391": "ty",
		"ISO6392": "tah",
		"ISO6392alt": [
		  "tah"
		]
	  },
	  "tg": {
		"name": "Tajik",
		"displayName": "Tajik",
		"displayNativeName": "Тоҷикӣ",
		"ISO6391": "tg",
		"ISO6392": "tgk",
		"ISO6392alt": [
		  "tgk"
		]
	  },
	  "ta": {
		"name": "Tamil",
		"displayName": "Tamil",
		"displayNativeName": "தமிழ்",
		"ISO6391": "ta",
		"ISO6392": "tam",
		"ISO6392alt": [
		  "tam"
		]
	  },
	  "tt": {
		"name": "Tatar",
		"displayName": "Tatar",
		"displayNativeName": "Tatarça",
		"ISO6391": "tt",
		"ISO6392": "tat",
		"ISO6392alt": [
		  "tat"
		]
	  },
	  "te": {
		"name": "Telugu",
		"displayName": "Telugu",
		"displayNativeName": "తెలుగు",
		"ISO6391": "te",
		"ISO6392": "tel",
		"ISO6392alt": [
		  "tel"
		]
	  },
	  "th": {
		"name": "Thai",
		"displayName": "Thai",
		"displayNativeName": "ไทย",
		"ISO6391": "th",
		"ISO6392": "tha",
		"ISO6392alt": [
		  "tha"
		]
	  },
	  "bo": {
		"name": "Tibetan",
		"displayName": "Tibetan",
		"displayNativeName": "Tibetan",
		"ISO6391": "bo",
		"ISO6392": "tib",
		"ISO6392alt": [
		  "tib",
		  "bod"
		]
	  },
	  "ti": {
		"name": "Tigrinya",
		"displayName": "Tigrinya",
		"displayNativeName": "ትግርኛ",
		"ISO6391": "ti",
		"ISO6392": "tir",
		"ISO6392alt": [
		  "tir"
		]
	  },
	  "to": {
		"name": "Tonga (Tonga Islands)",
		"displayName": "Tonga (Tonga Islands)",
		"displayNativeName": "Lea Faka-Tonga",
		"ISO6391": "to",
		"ISO6392": "ton",
		"ISO6392alt": [
		  "ton"
		]
	  },
	  "ts": {
		"name": "Tsonga",
		"displayName": "Tsonga",
		"displayNativeName": "Xitsonga",
		"ISO6391": "ts",
		"ISO6392": "tso",
		"ISO6392alt": [
		  "tso"
		]
	  },
	  "tn": {
		"name": "Tswana",
		"displayName": "Tswana",
		"displayNativeName": "Setswana",
		"ISO6391": "tn",
		"ISO6392": "tsn",
		"ISO6392alt": [
		  "tsn"
		]
	  },
	  "tr": {
		"name": "Turkish",
		"displayName": "Turkish",
		"displayNativeName": "Türkçe",
		"ISO6391": "tr",
		"ISO6392": "tur",
		"ISO6392alt": [
		  "tur"
		]
	  },
	  "tk": {
		"name": "Turkmen",
		"displayName": "Turkmen",
		"displayNativeName": "Туркмен",
		"ISO6391": "tk",
		"ISO6392": "tuk",
		"ISO6392alt": [
		  "tuk"
		]
	  },
	  "tw": {
		"name": "Twi",
		"displayName": "Twi",
		"displayNativeName": "Twi",
		"ISO6391": "tw",
		"ISO6392": "twi",
		"ISO6392alt": [
		  "twi"
		]
	  },
	  "ug": {
		"name": "Uighur; Uyghur",
		"displayName": "Uighur; Uyghur",
		"displayNativeName": "Uyƣurqə",
		"ISO6391": "ug",
		"ISO6392": "uig",
		"ISO6392alt": [
		  "uig"
		]
	  },
	  "uk": {
		"name": "Ukrainian",
		"displayName": "Ukrainian",
		"displayNativeName": "Українська",
		"ISO6391": "uk",
		"ISO6392": "ukr",
		"ISO6392alt": [
		  "ukr"
		]
	  },
	  "ur-PK": {
		"name": "Urdu",
		"displayName": "Urdu",
		"displayNativeName": "اردو",
		"ISO6391": "ur-PK",
		"ISO6392": "urd",
		"ISO6392alt": [
		  "urd"
		]
	  },
	  "uz": {
		"name": "Uzbek",
		"displayName": "Uzbek",
		"displayNativeName": "Ўзбек",
		"ISO6391": "uz",
		"ISO6392": "uzb",
		"ISO6392alt": [
		  "uzb"
		]
	  },
	  "ve": {
		"name": "Venda",
		"displayName": "Venda",
		"displayNativeName": "Tshivenḓa",
		"ISO6391": "ve",
		"ISO6392": "ven",
		"ISO6392alt": [
		  "ven"
		]
	  },
	  "vi": {
		"name": "Vietnamese",
		"displayName": "Vietnamese",
		"displayNativeName": "Việtnam",
		"ISO6391": "vi",
		"ISO6392": "vie",
		"ISO6392alt": [
		  "vie"
		]
	  },
	  "vo": {
		"name": "Volapük",
		"displayName": "Volapük",
		"displayNativeName": "Volapük",
		"ISO6391": "vo",
		"ISO6392": "vol",
		"ISO6392alt": [
		  "vol"
		]
	  },
	  "wa": {
		"name": "Walloon",
		"displayName": "Walloon",
		"displayNativeName": "Walon",
		"ISO6391": "wa",
		"ISO6392": "wln",
		"ISO6392alt": [
		  "wln"
		]
	  },
	  "cy": {
		"name": "Welsh",
		"displayName": "Welsh",
		"displayNativeName": "Cymraeg",
		"ISO6391": "cy",
		"ISO6392": "wel",
		"ISO6392alt": [
		  "wel",
		  "cym"
		]
	  },
	  "fy": {
		"name": "Western Frisian",
		"displayName": "Western Frisian",
		"displayNativeName": "Frysk",
		"ISO6391": "fy",
		"ISO6392": "fry",
		"ISO6392alt": [
		  "fry"
		]
	  },
	  "wo": {
		"name": "Wolof",
		"displayName": "Wolof",
		"displayNativeName": "Wollof",
		"ISO6391": "wo",
		"ISO6392": "wol",
		"ISO6392alt": [
		  "wol"
		]
	  },
	  "xh": {
		"name": "Xhosa",
		"displayName": "Xhosa",
		"displayNativeName": "isiXhosa",
		"ISO6391": "xh",
		"ISO6392": "xho",
		"ISO6392alt": [
		  "xho"
		]
	  },
	  "yi": {
		"name": "Yiddish",
		"displayName": "Yiddish",
		"displayNativeName": "ייִדיש",
		"ISO6391": "yi",
		"ISO6392": "yid",
		"ISO6392alt": [
		  "yid"
		]
	  },
	  "yo": {
		"name": "Yoruba",
		"displayName": "Yoruba",
		"displayNativeName": "Yorùbá",
		"ISO6391": "yo",
		"ISO6392": "yor",
		"ISO6392alt": [
		  "yor"
		]
	  },
	  "za": {
		"name": "Zhuang; Chuang",
		"displayName": "Zhuang; Chuang",
		"displayNativeName": "壮语",
		"ISO6391": "za",
		"ISO6392": "zha",
		"ISO6392alt": [
		  "zha"
		]
	  },
	  "zu": {
		"name": "Zulu",
		"displayName": "Zulu",
		"displayNativeName": "isiZulu",
		"ISO6391": "zu",
		"ISO6392": "zul",
		"ISO6392alt": [
		  "zul"
		]
	  }
	};
	
export function getCultures() {
	return cultures;
}

export function getCulture(ccode) {
	return cultures[ccode];
}

export default {
	matchCulture: matchCulture,
	getCultures: getCultures,
	getCulture: getCulture,
	getDictionaries: getDictionaries,
	getDictionary: getDictionary
};


/* eslint-enable indent */
